#!/bin/bash
#############################################################
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#
############################################################

fork_once() { [ $(pidof -sx $1) ] || $@ & }

# Startup
fork_once sxhkd
fork_once volumeicon &
fork_once greenclip daemon
fork_once dockd --daemon &
fork_once picom --config ~/.config/picom/picom.conf &
fork_once syndaemon -i 0.7 -d -K -t &


xset -b &
xset r rate 300 65 &
numlockx &
nm-applet --sm-disable &
setxkbmap -model pc105 -layout de,us -variant nodeadkeys -option compose:rctrl,grp:alt_shift_toggle

dunst_launch &
polybar_launch &
sleep 1.5
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fcitx &
~/.config/wpg/wp_restore.sh &

#Java fix
wmname LG3D
 
# setting up workspaces
python ~/dotfiles/bspwm/workspaces.py

bspc config top_monocle_padding 0
bspc config top_padding 30
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config click_to_focus button1
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config pointer_follows_monitor true

bspc config border_width 4
bspc config window_gap 8

bspc rule -a Pavucontrol state=floating center=true
bspc rule -a gmic_qt state=floating 
bspc rule -a Teams-Benachrichtigung state=floating 
bspc rule -a KeePassXC state=floating center=true 
bspc rule -a copyq state=floating 
bspc rule -a sun-awt-X11-XWindowPeer state=floating 
bspc rule -a Gnome-calculator state=floating 
bspc rule -a Seiteninformation* state=floating 
bspc rule -a Yad state=floating center=true
bspc rule -a TeamViewer state=floating 
bspc rule -a Wpg state=floating center=true

~/.config/bspwm/bspwm_colors.sh &
