#!/bin/bash
#############################################################
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#
############################################################

fork_once() { [ $(pidof -sx $1) ] || $@ & }

# Startup
fork_once sxhkd
fork_once volumeicon &
fork_once greenclip daemon

dunst &
dunst_launch &
xset r rate 300 65 &
polybar_launch &
sleep 1.5
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fcitx &
~/.config/wpg/wp_restore.sh &

#Java fix
wmname LG3D
 
bspc monitor eDP -d 一 ニ 三 四 五 六 七 八 九 十 
bspc monitor HDMI-A-0 -d I II III IV V VI VII VIII IX X
bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9 10

bspc config top_monocle_padding 0
bspc config top_padding 30
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true

bspc config border_width 4
bspc config window_gap 8

bspc rule -a Pavucontrol state=floating center=true
bspc rule -a gmic_qt state=floating 
bspc rule -a Teams-Benachrichtigung state=floating 
bspc rule -a KeePassXC state=floating center=true 
bspc rule -a copyq state=floating 
bspc rule -a sun-awt-X11-XWindowPeer state=floating 
bspc rule -a Gnome-calculator state=floating 
bspc rule -a Seiteninformation* state=floating 
bspc rule -a Yad state=floating center=true
bspc rule -a TeamViewer state=floating 
bspc rule -a Wpg state=floating center=true

~/.config/bspwm/bspwm_colors.sh &
