#!/bin/bash
#############################################################
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#
############################################################

fork_once() { [ "$(pidof -sx "$1")" ] || "$@" & }
relaunch() {
	if pgrep "$1"; then pkill "$1"; fi
	"$@" &
}

# Startup
fork_once greenclip daemon
fork_once picom --config ~/.config/picom/picom.conf
fork_once syndaemon -i 0.7 -d -K -t
relaunch dunst
relaunch sxhkd

xset -b &
xset r rate 300 65 &
nm-applet &
setxkbmap -layout eu &

"$HOME"/bin/polybar_launch &
sleep 1.5
polkit-agent & # symbolic link of /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
fcitx &
"$HOME"/.config/wpg/wp_restore.sh &
"$HOME"/.local/bin/noisetorch -i -t 90 > /dev/null 2>&1

#Java fix
wmname LG3D

# setting up workspaces (https://github.com/koopa1338/bspwm-workspaces)
"$HOME"/.cargo/bin/workspaces &

bspc config top_monocle_padding 0
bspc config top_padding 30
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config click_to_focus button1
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config pointer_follows_monitor true

bspc config border_width 3
bspc config window_gap 6

bspc rule -a Pavucontrol state=floating center=true
bspc rule -a gmic_qt state=floating
bspc rule -a Teams-Benachrichtigung state=floating
bspc rule -a KeePassXC state=floating center=true
bspc rule -a sun-awt-X11-XWindowPeer state=floating
bspc rule -a TeamViewer:*:TeamViewer state=floating
bspc rule -a Wpg state=floating center=true
bspc rule -a Blueman-manager state=floating center=true
bspc rule -a SpeedCrunch state=floating center=true
bspc rule -a Zathura state=tiled

"$HOME"/.config/bspwm/bspwm_colors.sh &
