#!/bin/bash
#############################################################
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#
############################################################

fork_once() { [ "$(pidof -sx $1)" ] || "$@" & }

# Startup
fork_once sxhkd
fork_once greenclip daemon
fork_once picom --config ~/.config/picom/picom.conf --experimental-backends
fork_once syndaemon -i 0.7 -d -K -t
fork_once gentoo-pipewire-launcher


xset -b &
xset r rate 300 65 &
nm-applet --sm-disable &
setxkbmap -model pc105 -layout de -variant nodeadkeys -option compose:rctrl,grp:alt_shift_toggle &

"$HOME"/bin/dunst_launch &
"$HOME"/bin/polybar_launch &
sleep 1.5
polkit-agent & # symbolic link of /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
fcitx &
"$HOME"/.config/wpg/wp_restore.sh &

#Java fix
wmname LG3D
 
# setting up workspaces (https://github.com/koopa1338/bspwm-workspaces)
"$HOME"/.cargo/bin/workspaces &

bspc config top_monocle_padding 0
bspc config top_padding 30
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config click_to_focus button1
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config pointer_follows_monitor true

bspc config border_width 3
bspc config window_gap 6

bspc rule -a Pavucontrol state=floating center=true
bspc rule -a gmic_qt state=floating 
bspc rule -a Teams-Benachrichtigung state=floating 
bspc rule -a KeePassXC state=floating center=true 
bspc rule -a copyq state=floating 
bspc rule -a sun-awt-X11-XWindowPeer state=floating 
bspc rule -a Gnome-calculator state=floating 
bspc rule -a Seiteninformation* state=floating 
bspc rule -a Yad state=floating center=true
bspc rule -a TeamViewer state=floating 
bspc rule -a Wpg state=floating center=true
bspc rule -a Blueman-manager state=floating center=true
bspc rule -a SpeedCrunch state=floating center=true
bspc rule -a Zathura state=tiled

"$HOME"/.config/bspwm/bspwm_colors.sh &
