vim.cmd("packadd nvim-lspconfig")
vim.cmd("packadd completion-nvim")
vim.cmd("packadd popup.nvim")
vim.cmd("packadd plenary.nvim")
vim.cmd("packadd telescope.nvim")
vim.cmd("packadd nvim-treesitter")
vim.cmd("packadd ultisnips")
vim.cmd("packadd express_line.nvim")
