local Color, colors, Group, groups, styles = require("colorbuddy").setup()

Color.new('black'       ,'#3E2224')
Color.new('darkblue'    ,'#9A7686')
Color.new('darkgreen'   ,'#DBA294')
Color.new('darkcyan'    ,'#ECAC8B')
Color.new('darkred'     ,'#646A92')
Color.new('darkmagenta' ,'#AD97A0')
Color.new('brown'       ,'#6F87D3')
Color.new('gray'        ,'#EFDBCD')
Color.new('darkgray'    ,'#5E3336')
Color.new('blue'        ,'#D987AC')
Color.new('green'       ,'#FFC4A8')
Color.new('cyan'        ,'#FFD79C')
Color.new('red'         ,'#727ECD')
Color.new('magenta'     ,'#F5AFCC')
Color.new('yellow'      ,'#FFFBEB')
Color.new('white'       ,'#FFFBEB')
