local Color, colors, Group, groups, styles = require("colorbuddy").setup()

Color.new('background'    ,  "#3B4252")
Color.new('fg'            ,  "#292929")
Color.new('color_0'       ,  "#2E3440")
Color.new('color_1'       ,  "#3B4252")
Color.new('color_2'       ,  "#434C5E")
Color.new('color_3'       ,  "#4C566A")
Color.new('color_3_light' ,  "#4D576B")
Color.new('color_4'       ,  "#D8DEE9")
Color.new('color_5'       ,  "#E5E9F0")
Color.new('color_6'       ,  "#ECEFF4")
Color.new('color_7'       ,  "#8FBCBB")
Color.new('color_8'       ,  "#88C0D0")
Color.new('color_9'       ,  "#81A1C1")
Color.new('color_10'      ,  "#5E81AC")
Color.new('color_11'      ,  "#BF616A")
Color.new('color_12'      ,  "#D08770")
Color.new('color_13'      ,  "#EBCB8B")
Color.new('color_14'      ,  "#A3BE8C")
Color.new('color_15'      ,  "#B48EAD")


-- my highlight
Group.new('TabLineSel',          colors.fg,           colors.blue, styles.bold )
Group.new('TabLineSelSeparator', colors.blue,         colors.none)
Group.new('TabLine', colors.color_4, colors.color_2)
Group.new('TabLineSeparator', colors.color_2, colors.none)

Group.new('Conceal',             colors.color_3_light, colors.none)
Group.new('VertSplit', colors.color_3, colors.none)

Group.new('Normal',         colors.none,         colors.none)
Group.new('Function',       colors.color_8,       colors.none,    styles.bold)
Group.new('Error',          colors.color_11,      colors.none,    styles.bold)
Group.new('ErrorMsg',       colors.color_5,       colors.color_11, styles.bold)
Group.new('WarningMsg',     colors.color_5,       colors.color_12, styles.bold)
Group.new('Boolean',        colors.color_9,       colors.none,    styles.NONE)
Group.new('Character',      colors.color_14,      colors.none,    styles.NONE)
Group.new('Comment',        colors.color_3_light, colors.none,    styles.NONE)
Group.new("Conditional",    colors.color_9,       colors.none,    styles.NONE)
Group.new("Constant",       colors.color_4,       colors.none,    styles.NONE)
Group.new("Define",         colors.color_9,       colors.none,    styles.NONE)
Group.new("Delimiter",      colors.color_6,       colors.none,    styles.NONE)
Group.new("Exception",      colors.color_9,       colors.none,    styles.NONE)
Group.new("Float",          colors.color_15,      colors.none,    styles.NONE)
Group.new("Function",       colors.color_8,       colors.none,    styles.NONE)
Group.new("Identifier",     colors.color_4,       colors.none,    styles.NONE)
Group.new("Include",        colors.color_9,       colors.none,    styles.NONE)
Group.new("Keyword",        colors.color_9,       colors.none,    styles.italic)
Group.new("Label",          colors.color_9,       colors.none,    styles.italic)
Group.new("Number",         colors.color_15,      colors.none,    styles.NONE)
Group.new("Operator",       colors.color_9,       colors.none,    styles.NONE)
Group.new("PreProc",        colors.color_9,       colors.none,    styles.NONE)
Group.new("Repeat",         colors.color_9,       colors.none,    styles.NONE)
Group.new("Special",        colors.color_4,       colors.none,    styles.NONE)
Group.new("SpecialChar",    colors.color_13,      colors.none,    styles.NONE)
Group.new("SpecialComment", colors.color_8,       colors.none,    styles.NONE)
Group.new("Statement",      colors.color_9,       colors.none,    styles.NONE)
Group.new("StorageClass",   colors.color_9,       colors.none,    styles.NONE)
Group.new("String",         colors.color_14,      colors.none,    styles.NONE)
Group.new("Structure",      colors.color_9,       colors.none,    styles.NONE)
Group.new("Tag",            colors.color_4,       colors.none,    styles.NONE)
Group.new("Title",          colors.color_4,       colors.none)
Group.new("Todo",           colors.color_13,      colors.none,    styles.NONE)
Group.new("Type",           colors.color_9,       colors.none,    styles.italic)
Group.new("Typedef",        colors.color_9,       colors.none,    styles.NONE)
Group.new("CursorColumn",   colors.color_1,       colors.none,    styles.NONE)
Group.new("LineNr",         colors.color_9,       colors.none,    styles.NONE)
Group.new("CursorLineNr",   colors.color_5,       colors.none,    styles.NONE)
Group.new("Line",           colors.color_12,      colors.none,    styles.bold)
Group.new("SignColumn",     colors.none,         colors.none,    styles.NONE)

Group.new("ColorColumn", colors.none, colors.color_1)
Group.new("Cursor", colors.color_0, colors.color_4)
Group.new("CursorLine", colors.none, colors.color_0)
Group.new("iCursor",colors.color_0, colors.color_4)
Group.new("EndOfBuffer",colors.none, colors.none)
Group.new("MatchParen",colors.color_8, colors.color_3)
Group.new("NonText",colors.none, colors.none)
Group.new("PMenu", colors.color_4, colors.color_2)
Group.new("PmenuSbar", colors.color_4, colors.color_2)
Group.new("PMenuSel", colors.color_6, colors.color_9)
Group.new("PmenuThumb", colors.color_8, colors.color_3)
Group.new("SpecialKey",colors.color_3, colors.color_3)
Group.new("SpellBad",colors.color_11, colors.color_0)
Group.new("SpellCap",colors.color_13, colors.color_0)
Group.new("SpellLocal",colors.color_5, colors.color_0)
Group.new("SpellRare",colors.color_6, colors.color_0)
Group.new("Visual",colors.color_4, colors.color_9)
Group.new("VisualNOS",colors.color_2, colors.color_1)

-- "+- Neovim Support -+
Group.new("healthError",colors.color_11, colors.color_1)
Group.new("healthSuccess",colors.color_14, colors.color_1)
Group.new("healthWarning",colors.color_13, colors.color_1)
Group.new("TermCursorNC",colors.color_1, colors.color_1)
Group.new("IncSearch",colors.color_6, colors.color_10, styles.underline)
Group.new("Search",colors.color_1, colors.color_8)

-- vim
Group.new('vimcommand',      groups.Statement, colors.none)
Group.new('vimLet',          groups.vimcommand , colors.none)
Group.new('vimFuncVar',      groups.identifier, colors.none)
Group.new('vimCommentTitle', groups.PreProc, colors.none)
Group.new('vimIsCommand',    colors.none, colors.none)
Group.new('vimFuncSID',      groups.Special, colors.none)
Group.new('vimMapModKey',    groups.vimFuncSID, colors.none)
Group.new('vimMapLhs',       colors.none, colors.none)
Group.new('vimNotation',     colors.color_7, colors.none)
Group.new('vimBracket',      groups.Delimiter, colors.none)
Group.new('vimMap',          groups.vimcommand, colors.none)
Group.new('nvimMap',         groups.vimMap, colors.none)

-- startify
Group.new("StartifyFile",colors.color_6, colors.none)
Group.new("StartifyFooter",colors.none, colors.none)
Group.new("StartifyHeader",colors.color_8, colors.none)
Group.new("StartifyNumber",colors.color_7, colors.none)
Group.new("StartifyPath",colors.color_8, colors.none)
Group.new("StartifyBracket", groups.Delimiter, groups.Delimiter)
Group.new("StartifySlash", groups.Normal, groups.Normal)
Group.new("StartifySpecial", groups.Comment, groups.Comment)

-- gitgutter
Group.new("GitGutterAdd",          colors.color_14, colors.none)
Group.new("GitGutterDelete",       colors.color_11, colors.none)
Group.new("GitGutterChange",       colors.color_13, colors.none)
Group.new("GitGutterChangeDelete", colors.color_11, colors.none)

-- built-in LSP
Group.new("LSPDiagnosticsWarning", colors.color_13, colors.none)
Group.new("LSPDiagnosticsError", colors.color_11, colors.none)
Group.new("LSPDiagnosticsInformation", colors.color_8, colors.none)
Group.new("LSPDiagnosticsHint", colors.color_10, colors.none)

-- TS
Group.new("TSDefinition", groups.Type, groups.Type, styles.italic)
Group.new("TSString", groups.String, groups.String, styles.italic)
Group.new("TSDefinitionUsage", groups.CursorLine, groups.CursorLine)

-- TeleScope
Group.new("TelescopeSelection", colors.color_11, colors.color_8, styles.bold)
Group.new("TelescopeNormal", groups.Pmenu, groups.Pmenu)
