local Color, colors, Group, groups, styles = require("colorbuddy").setup()

Color.new('wpg_0'  ,'#090B3B')
Color.new('wpg_1'  ,'#386188')
Color.new('wpg_2'  ,'#4C7495')
Color.new('wpg_3'  ,'#5F9CA7')
Color.new('wpg_4'  ,'#73CDB5')
Color.new('wpg_5'  ,'#90AEA6')
Color.new('wpg_6'  ,'#99DEAF')
Color.new('wpg_7'  ,'#c9ecdb')
Color.new('wpg_8'  ,'#0f1266')
Color.new('wpg_9'  ,'#3c7ebd')
Color.new('wpg_10' ,'#5498d0')
Color.new('wpg_11' ,'#6ad6ea')
Color.new('wpg_12' ,'#80fff4')
Color.new('wpg_13' ,'#a6f6e1')
Color.new('wpg_14' ,'#aeffda')
Color.new('wpg_15' ,'#eaffff')

Color.new('Black'       ,'#090B3B' )
Color.new('DarkRed'     ,'#386188' )
Color.new('DarkGreen'   ,'#4C7495' )
Color.new('Brown'       ,'#5F9CA7' )
Color.new('DarkBlue'    ,'#73CDB5' )
Color.new('DarkMagenta' ,'#90AEA6' )
Color.new('DarkCyan'    ,'#99DEAF' )
Color.new('LightGray'   ,'#c9ecdb' )
Color.new('DarkGray'    ,'#0f1266' )
Color.new('Red'         ,'#3c7ebd' )
Color.new('Green'       ,'#5498d0' )
Color.new('Yellow'      ,'#6ad6ea' )
Color.new('Blue'        ,'#80fff4' )
Color.new('Magenta'     ,'#a6f6e1' )
Color.new('Cyan'        ,'#aeffda' )
Color.new('White'       ,'#eaffff' )

Color.new('seagreen',  '#698b69')
Color.new('turquoise', '#698b69')

Color.new('diffadd', '#0a5c2c')
Color.new('diffdel', '#570f18')

Group.new('Normal'            , colors.wpg_15      , colors.wpg_0)
Group.new("User1"             , colors.wpg_15      , colors.wpg_6)
Group.new("User2"             , colors.wpg_15      , colors.wpg_8)
Group.new("Title"             , colors.wpg_5       , colors.none)
Group.new("TabLineFill"       , colors.wpg_15      , colors.wpg_8)
Group.new("TabLine"           , colors.wpg_15      , colors.wpg_8)
Group.new("TabLineSel"        , colors.wpg_0       , colors.wpg_14)
Group.new("StatusLine"        , colors.wpg_0       , colors.wpg_14)
Group.new("StatusLineNC"      , colors.wpg_15      , colors.wpg_8)
Group.new("StatusLineTerm"    , colors.wpg_12      , colors.wpg_0)
Group.new("StatusLineTermNC"  , colors.wpg_15      , colors.wpg_8)
Group.new("CursorLine"        , colors.wpg_0       , colors.none)
Group.new("Visual"            , colors.wpg_0       , colors.wpg_14)
Group.new("CursorLineNr"      , colors.wpg_15      , colors.wpg_6)
Group.new("LineNr"            , colors.wpg_7       , colors.wpg_8)
Group.new("VertSplit"         , colors.wpg_0       , colors.wpg_8)
Group.new("Specialkey"        , colors.wpg_13      , colors.wpg_0)
Group.new("ErrorMsg"          , colors.wpg_0       , colors.wpg_9)
Group.new("Pmenu"             , colors.wpg_15      , colors.wpg_8)
Group.new("PmenuSbar"         , colors.wpg_4      , colors.wpg_2)
Group.new("PmenuSel"          , colors.wpg_0       , colors.wpg_14)
Group.new("PmenuThumb"        , colors.wpg_8      , colors.wpg_3)
Group.new("SpellBad"          , colors.wpg_8       , colors.wpg_9)
Group.new("Comment"           , colors.wpg_4       , colors.wpg_0        , styles.italic)
Group.new("MatchParen"        , colors.wpg_12      , colors.wpg_8)
Group.new("DiffAdd"           , colors.none        , colors.diffadd)
Group.new("DiffDelete"        , colors.none        , colors.diffdel)
Group.new("DiffText"          , colors.wpg_0       , colors.none)
Group.new("DiffChange"        , colors.wpg_0       , colors.none)
Group.new("YCMWarningSection" , colors.wpg_0       , colors.wpg_4)
Group.new("WarningMsg"        , colors.wpg_10      , colors.none)
Group.new("MoreMsg"           , colors.wpg_15      , colors.none)
Group.new("Directory"         , colors.wpg_11      , colors.none)
Group.new("Folded"            , colors.wpg_15      , colors.wpg_8)

Group.new("ColorColumn"       , colors.none        , colors.wpg_1)
Group.new("Cursor"            , colors.wpg_0      , colors.wpg_4)
Group.new("iCursor"           , colors.wpg_0      , colors.wpg_4)
Group.new("EndOfBuffer"       , colors.none        , colors.none)
Group.new("NonText"           , colors.none        , colors.none)
Group.new("SpellCap"          , colors.wpg_13     , colors.wpg_0)
Group.new("SpellLocal"        , colors.wpg_5      , colors.wpg_0)
Group.new("SpellRare"         , colors.wpg_6      , colors.wpg_0)
Group.new("VisualNOS"         , colors.wpg_2      , colors.wpg_1)

Group.new("Constant"          , colors.wpg_11      , colors.none)
Group.new("Identifier"        , colors.wpg_12      , colors.none)
Group.new("Statement"         , colors.wpg_10      , colors.none)
Group.new("Keyword"           , colors.wpg_13      , colors.none)
Group.new("Conditional"       , colors.wpg_11      , colors.none)
Group.new("Number"            , colors.wpg_12      , colors.none)
Group.new("PreProc"           , colors.wpg_10      , colors.none)
Group.new("Type"              , colors.wpg_13      , colors.none         , styles.italic)
Group.new("Ignore"            , colors.wpg_0       , colors.none)
Group.new("Error"             , colors.wpg_0       , colors.wpg_1)
Group.new("Todo"              , colors.wpg_15      , colors.wpg_8)
Group.new("SignColumn"        , colors.wpg_12      , colors.wpg_8)
Group.new("Search"            , colors.wpg_0       , colors.wpg_12)

Group.new("Question"          , groups.Type        , groups.Type)
Group.new("FoldColumn"        , groups.Folded      , groups.Folded)

Group.new("Special"           , groups.Type        , groups.Type)
Group.new("String"            , groups.Constant    , groups.Constant)
Group.new("Character"         , groups.Constant    , groups.Constant)
Group.new("Boolean"           , groups.Statement   , groups.Statement)
Group.new("Repeat"            , groups.Conditional , groups.Conditional)
Group.new("Label"             , groups.Type        , groups.Type)
Group.new("Operator"          , groups.Type        , groups.Type)
Group.new("Include"           , groups.PreProc     , groups.PreProc)
Group.new("Define"            , groups.PreProc     , groups.PreProc)
Group.new("Macro"             , groups.PreProc     , groups.PreProc)
Group.new("PreCondit"         , groups.PreProc     , groups.PreProc)
Group.new("StorageClass"      , groups.Type        , groups.Type)
Group.new("Structure"         , groups.Type        , groups.Type)
Group.new("Tag"               , groups.Special     , groups.Special)
Group.new("Debug"             , groups.Special     , groups.Special)
Group.new("Typedef"           , groups.Type        , groups.Type)

Group.new('Conceal'        , colors.wpg_3  , colors.none)
Group.new('Function'       , colors.wpg_9  , colors.none  , styles.bold)
Group.new("Delimiter"      , colors.wpg_6  , colors.none  , styles.NONE)
Group.new("Exception"      , colors.wpg_9  , colors.none  , styles.NONE)
Group.new("Float"          , colors.wpg_15 , colors.none  , styles.NONE)
Group.new("SpecialChar"    , colors.wpg_13 , colors.none  , styles.NONE)
Group.new("CursorColumn"   , colors.wpg_1  , colors.none  , styles.NONE)
Group.new("Line"           , colors.wpg_12 , colors.none  , styles.bold)
Group.new("SpecialComment" , colors.wpg_8  , colors.none  , styles.NONE)

