#fish_vi_key_bindings
#wpg -t
#kitty + complete setup fish | source
set fish_color_param normal
set fish_color_command normal
set fish_color_autosuggestion normal
set fish_color_quote normal
alias v="vim"
alias r="ranger"
alias sr="sudo -E ranger"
alias h="htop -d5"
alias grep="grep --color=auto"
alias nf="neofetch"
alias vrc="vim /home/koopa/dotfiles/vimrc"
alias cu="checkupdates"
alias e="exit"
alias ls="ls -hN --color=auto --group-directories-first"
alias lsa="ls -a"
alias ..="cd .."
alias cdu="cd /home/koopa/Dokumente/Uni"
alias ...="cd ../.."
abbr gita="git add"
abbr giti="git init"
abbr gitc="git commit"
abbr gitch="git checkout"
abbr gits="git status"
abbr gitp="git push"
abbr gitpl="git pull"
abbr gitcl="git clone"
alias pup="trizen -Syu"
alias p="trizen"
alias cpc="cleanpaccache"
alias vbib="vim /home/koopa/latex/Bibliothek.bib"
alias vconf="vim /home/koopa/dotfiles/config"
alias rmdir="rm -d"
alias untar="tar -zxvf"
alias ipe="curl ipinfo.io/country; and curl ipinfo.io/ip"
#alias ipi="ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/'"
alias lsenum="ls | wc -l"
alias speed="speedtest --simple"
alias yv="youtube-viewer"
alias ydl="youtube-dl"
