#fish_vi_key_bindings
wpg -t
set fish_color_param normal
set fish_color_command normal
set fish_color_autosuggestion normal
set fish_color_quote normal
alias v="vim"
alias r="ranger"
alias sr="sudo ranger"
alias grep="grep --color=auto"
alias nf="neofetch"
alias vrc="vim /home/koopa/dotfiles/vimrc"
alias cu="checkupdates"
alias e="exit"
alias lsa="ls -al"
alias ls="ls -hN --color=auto --group-directories-first"
alias ..="cd .."
alias cdu="cd /home/koopa/Dokumente/Uni"
alias ...="cd ../.."
alias gita="git add"
alias giti="git init"
alias gitc="git commit"
alias gitch="git checkout"
alias gits="git status"
alias gitp="git push"
alias gitpl="git pull"
alias gitcl="git clone"
alias pup="trizen -Syu"
alias p="trizen"
alias cpc="cleanpaccache"
alias vbib="vim /home/koopa/latex/Bibliothek.bib"
alias rmdir="rm -d"
alias untar="tar -zxvf"
alias ipe="curl ipinfo.io/country; and curl ipinfo.io/ip"
alias lsenum="ls | wc -l"
alias speed="speedtest --simple"
